### ISSUE TITLE
Simplify args for standard noise tests

### ISSUE THREAD

**Issue by peter-madigan** [samkohn/larpix-scripts#6]
Come up with a scheme so that a user can run the default scripts with no/very few arguments.
E.g. use a config/ directory to store default configurations to load

**Comment by samkohn** [comment]
I've been thinking about setting up a directory structure per fill. For example:

- fill-2018-04-06/
  - geometry.yaml
  - datalog/
  - pedestal/
  - calibration/
  - etc.
- fill-2018-04-07/
- etc.

Then you could run scripts and just pass in the directory for the particular fill, and all of the required data would be there.

**Comment by peter-madigan** [comment]
I like the approach of consolidating all of the data for a given run, but this still requires the user to specify the directory for the fill. Maybe instead of splitting it up based on fill, we only use the date: e.g.
`data/YYYY-MM-DD/`
    `datalog/`
    `pedestal/`
    `calibration/`
    etc
This way scripts can automatically generate a directory if needed, and populate the directory with default config files/etc.
Scripts would search for configuration files in this order:
- if `--configuration` flag not specified: 
    - look for files matching `<board>-<io chain>-c<chip id>_config.json in data/YYYY-MM-DD/default_config/`
    - if chip config not found, look for file `default_config.json` in `data/YYYY-MM-DD/default_config/`
    - if directory not found, create directory `data/YYYY-MM-DD` and `data/YYYY-MM-DD/default_config` and generate the file `default_config.json` as the default configuration file of the script (currently `physics.json`)
- if `--configuration` specifies a directory:
    - attempt to load configurations files in directory matching `<board>-<io chain>-c<chip id>_config.json`
    - if not found, disable chip (and warn)
if `--configuration` specifies a `.json` file:
    - load this configuration file

**Comment by samkohn** [comment]
That would work fine. We'll have to update the scripts anyways when we transition to the new data format. A bonus is that the data files will include the configurations so that will get easier.

**Comment by peter-madigan** [comment]
PR #8 will address this issue
